/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Dura2D: typeof import('./src/components/icons/Dura2D.vue')['default']
    ExperienceItem: typeof import('./src/components/ExperienceItem.vue')['default']
    FilterTabs: typeof import('./src/components/FilterTabs.vue')['default']
    GiscusComments: typeof import('./src/components/GiscusComments.vue')['default']
    GlslShaders: typeof import('./src/components/GlslShaders.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    LeveGL: typeof import('./src/components/icons/LeveGL.vue')['default']
    ListLabs: typeof import('./src/components/ListLabs.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    MediaCarousel: typeof import('./src/components/MediaCarousel.vue')['default']
    PhotoGallery: typeof import('./src/components/photos/PhotoGallery.vue')['default']
    PhotoGalleryAll: typeof import('./src/components/photos/PhotoGalleryAll.vue')['default']
    PhotoGrid: typeof import('./src/components/photos/PhotoGrid.vue')['default']
    PhotoSlide: typeof import('./src/components/photos/PhotoSlide.vue')['default']
    PostRow: typeof import('./src/components/PostRow.vue')['default']
    ProfileLinks: typeof import('./src/components/ProfileLinks.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectThumb: typeof import('./src/components/ProjectThumb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedWork: typeof import('./src/components/SelectedWork.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Vulkano: typeof import('./src/components/icons/Vulkano.vue')['default']
    WrapperLab: typeof import('./src/components/WrapperLab.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
    WrapperProject: typeof import('./src/components/WrapperProject.vue')['default']
  }
}
