packages: []

catalogs:
  build:
    '@giscus/vue': ^3.1.1
    '@mdit/plugin-footnote': ^0.22.2
    '@mdit/plugin-img-lazyload': ^0.22.1
    '@mdit/plugin-mathjax': ^0.23.1
    '@mdit/plugin-snippet': ^0.22.2
    '@shikijs/colorized-brackets': ^3.13.0
    '@shikijs/markdown-it': ^3.13.0
    '@shikijs/transformers': ^3.13.0
    '@shikijs/twoslash': ^3.13.0
    '@unocss/preset-web-fonts': ^66.5.2
    '@vitejs/plugin-vue': ^6.0.1
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^1.1.0
    sass-embedded: ^1.93.2
    shiki-transformer-copy-button: ^0.0.5
    unocss: ^66.5.2
    unplugin-auto-import: ^20.2.0
    unplugin-icons: ^22.4.1
    unplugin-vue-components: ^29.1.0
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.15.0
    vite: ^7.1.7
    vite-plugin-inspect: ^11.3.3
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^28.1.0
    vite-svg-loader: ^5.1.0
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@iconify/json': ^2.2.390
    ansis: ^4.2.0
    cross-env: ^10.1.0
    degit: ^2.8.4
    diacritics: ^1.3.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    exifreader: ^4.32.0
    fast-glob: ^3.3.3
    feed: ^5.1.0
    fs-extra: ^11.3.2
    lint-staged: ^16.2.3
    pathe: ^2.0.3
    pnpm: ^10.17.1
    prompts: ^2.4.2
    rimraf: ^6.0.1
    sharp: 0.34.3
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.6
    typescript: ~5.9.3
  frontend:
    '@unhead/vue': ^2.0.17
    '@unocss/reset': ^66.5.2
    '@vueuse/core': ^13.9.0
    dayjs: ^1.11.18
    nprogress: ^0.2.0
    pinia: ^3.0.3
    shiki: ^3.13.0
    shiki-magic-move: ^1.2.0
    vue: ^3.5.22
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/degit': ^2.8.6
    '@types/diacritics': ^1.3.3
    '@types/fs-extra': ^11.0.4
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^24.6.1
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9

onlyBuiltDependencies:
  - esbuild
  - exifreader
  - sharp
  - simple-git-hooks
  - unrs-resolver
