packages: []

catalogs:
  build:
    '@mdit/plugin-img-lazyload': ^0.22.1
    '@mdit/plugin-mathjax': ^0.23.1
    '@mdit/plugin-snippet': ^0.22.2
    '@shikijs/colorized-brackets': ^3.7.0
    '@shikijs/markdown-it': ^3.6.0
    '@shikijs/transformers': ^3.6.0
    '@shikijs/twoslash': ^3.6.0
    '@unocss/preset-web-fonts': ^66.1.4
    '@vitejs/plugin-vue': ^5.2.4
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^0.9.0
    sass-embedded: ^1.89.2
    shiki-transformer-copy-button: ^0.0.5
    unocss: ^66.1.4
    unplugin-auto-import: ^19.3.0
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^7.0.0
    vite-plugin-inspect: ^11.1.0
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^27.0.1
    vite-svg-loader: ^5.1.0
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@iconify/json': ^2.2.347
    cross-env: ^7.0.3
    degit: ^2.8.4
    diacritics: ^1.3.0
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    fs-extra: ^11.3.0
    lint-staged: ^16.1.0
    pnpm: ^10.12.1
    rimraf: ^6.0.1
    sharp: 0.32.6
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.19.4
    typescript: ~5.8.3
  frontend:
    '@unhead/vue': ^2.0.10
    '@unocss/reset': ^66.1.4
    '@vueuse/core': ^13.4.0
    dayjs: ^1.11.13
    nprogress: ^0.2.0
    pinia: ^3.0.3
    shiki: ^3.6.0
    shiki-magic-move: ^1.1.0
    vue: ^3.5.17
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/degit': ^2.8.6
    '@types/diacritics': ^1.3.3
    '@types/fs-extra': ^11.0.4
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^22.15.30
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - esbuild
  - exifreader
  - sharp
  - simple-git-hooks
  - unrs-resolver
